/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "inference.networking.x-k8s.io/llm-instance-gateway/api/v1alpha1"
	apiv1alpha1 "inference.networking.x-k8s.io/llm-instance-gateway/client-go/applyconfiguration/api/v1alpha1"
	scheme "inference.networking.x-k8s.io/llm-instance-gateway/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InferenceModelsGetter has a method to return a InferenceModelInterface.
// A group's client should implement this interface.
type InferenceModelsGetter interface {
	InferenceModels(namespace string) InferenceModelInterface
}

// InferenceModelInterface has methods to work with InferenceModel resources.
type InferenceModelInterface interface {
	Create(ctx context.Context, inferenceModel *v1alpha1.InferenceModel, opts v1.CreateOptions) (*v1alpha1.InferenceModel, error)
	Update(ctx context.Context, inferenceModel *v1alpha1.InferenceModel, opts v1.UpdateOptions) (*v1alpha1.InferenceModel, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, inferenceModel *v1alpha1.InferenceModel, opts v1.UpdateOptions) (*v1alpha1.InferenceModel, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.InferenceModel, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.InferenceModelList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InferenceModel, err error)
	Apply(ctx context.Context, inferenceModel *apiv1alpha1.InferenceModelApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.InferenceModel, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, inferenceModel *apiv1alpha1.InferenceModelApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.InferenceModel, err error)
	InferenceModelExpansion
}

// inferenceModels implements InferenceModelInterface
type inferenceModels struct {
	*gentype.ClientWithListAndApply[*v1alpha1.InferenceModel, *v1alpha1.InferenceModelList, *apiv1alpha1.InferenceModelApplyConfiguration]
}

// newInferenceModels returns a InferenceModels
func newInferenceModels(c *ApiV1alpha1Client, namespace string) *inferenceModels {
	return &inferenceModels{
		gentype.NewClientWithListAndApply[*v1alpha1.InferenceModel, *v1alpha1.InferenceModelList, *apiv1alpha1.InferenceModelApplyConfiguration](
			"inferencemodels",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.InferenceModel { return &v1alpha1.InferenceModel{} },
			func() *v1alpha1.InferenceModelList { return &v1alpha1.InferenceModelList{} }),
	}
}
