/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "inference.networking.x-k8s.io/llm-instance-gateway/api/v1alpha1"
	apiv1alpha1 "inference.networking.x-k8s.io/llm-instance-gateway/client-go/applyconfiguration/api/v1alpha1"
	scheme "inference.networking.x-k8s.io/llm-instance-gateway/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// InferencePoolsGetter has a method to return a InferencePoolInterface.
// A group's client should implement this interface.
type InferencePoolsGetter interface {
	InferencePools(namespace string) InferencePoolInterface
}

// InferencePoolInterface has methods to work with InferencePool resources.
type InferencePoolInterface interface {
	Create(ctx context.Context, inferencePool *v1alpha1.InferencePool, opts v1.CreateOptions) (*v1alpha1.InferencePool, error)
	Update(ctx context.Context, inferencePool *v1alpha1.InferencePool, opts v1.UpdateOptions) (*v1alpha1.InferencePool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, inferencePool *v1alpha1.InferencePool, opts v1.UpdateOptions) (*v1alpha1.InferencePool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.InferencePool, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.InferencePoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InferencePool, err error)
	Apply(ctx context.Context, inferencePool *apiv1alpha1.InferencePoolApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.InferencePool, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, inferencePool *apiv1alpha1.InferencePoolApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.InferencePool, err error)
	InferencePoolExpansion
}

// inferencePools implements InferencePoolInterface
type inferencePools struct {
	*gentype.ClientWithListAndApply[*v1alpha1.InferencePool, *v1alpha1.InferencePoolList, *apiv1alpha1.InferencePoolApplyConfiguration]
}

// newInferencePools returns a InferencePools
func newInferencePools(c *ApiV1alpha1Client, namespace string) *inferencePools {
	return &inferencePools{
		gentype.NewClientWithListAndApply[*v1alpha1.InferencePool, *v1alpha1.InferencePoolList, *apiv1alpha1.InferencePoolApplyConfiguration](
			"inferencepools",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.InferencePool { return &v1alpha1.InferencePool{} },
			func() *v1alpha1.InferencePoolList { return &v1alpha1.InferencePoolList{} }),
	}
}
