/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "inference.k8s.io/llm-instance-gateway/api/v1alpha1"
	applyconfigurationapiv1alpha1 "inference.k8s.io/llm-instance-gateway/client-go/applyconfiguration/api/v1alpha1"
	scheme "inference.k8s.io/llm-instance-gateway/client-go/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LLMServerPoolsGetter has a method to return a LLMServerPoolInterface.
// A group's client should implement this interface.
type LLMServerPoolsGetter interface {
	LLMServerPools(namespace string) LLMServerPoolInterface
}

// LLMServerPoolInterface has methods to work with LLMServerPool resources.
type LLMServerPoolInterface interface {
	Create(ctx context.Context, lLMServerPool *apiv1alpha1.LLMServerPool, opts v1.CreateOptions) (*apiv1alpha1.LLMServerPool, error)
	Update(ctx context.Context, lLMServerPool *apiv1alpha1.LLMServerPool, opts v1.UpdateOptions) (*apiv1alpha1.LLMServerPool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, lLMServerPool *apiv1alpha1.LLMServerPool, opts v1.UpdateOptions) (*apiv1alpha1.LLMServerPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.LLMServerPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.LLMServerPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.LLMServerPool, err error)
	Apply(ctx context.Context, lLMServerPool *applyconfigurationapiv1alpha1.LLMServerPoolApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.LLMServerPool, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, lLMServerPool *applyconfigurationapiv1alpha1.LLMServerPoolApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.LLMServerPool, err error)
	LLMServerPoolExpansion
}

// lLMServerPools implements LLMServerPoolInterface
type lLMServerPools struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.LLMServerPool, *apiv1alpha1.LLMServerPoolList, *applyconfigurationapiv1alpha1.LLMServerPoolApplyConfiguration]
}

// newLLMServerPools returns a LLMServerPools
func newLLMServerPools(c *ApiV1alpha1Client, namespace string) *lLMServerPools {
	return &lLMServerPools{
		gentype.NewClientWithListAndApply[*apiv1alpha1.LLMServerPool, *apiv1alpha1.LLMServerPoolList, *applyconfigurationapiv1alpha1.LLMServerPoolApplyConfiguration](
			"llmserverpools",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.LLMServerPool { return &apiv1alpha1.LLMServerPool{} },
			func() *apiv1alpha1.LLMServerPoolList { return &apiv1alpha1.LLMServerPoolList{} }),
	}
}
