/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "inference.networking.x-k8s.io/llm-instance-gateway/api/v1alpha1"
	apiv1alpha1 "inference.networking.x-k8s.io/llm-instance-gateway/client-go/applyconfiguration/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInferencePools implements InferencePoolInterface
type FakeInferencePools struct {
	Fake *FakeApiV1alpha1
	ns   string
}

var inferencepoolsResource = v1alpha1.SchemeGroupVersion.WithResource("inferencepools")

var inferencepoolsKind = v1alpha1.SchemeGroupVersion.WithKind("InferencePool")

// Get takes name of the inferencePool, and returns the corresponding inferencePool object, and an error if there is any.
func (c *FakeInferencePools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InferencePool, err error) {
	emptyResult := &v1alpha1.InferencePool{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(inferencepoolsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.InferencePool), err
}

// List takes label and field selectors, and returns the list of InferencePools that match those selectors.
func (c *FakeInferencePools) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InferencePoolList, err error) {
	emptyResult := &v1alpha1.InferencePoolList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(inferencepoolsResource, inferencepoolsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.InferencePoolList{ListMeta: obj.(*v1alpha1.InferencePoolList).ListMeta}
	for _, item := range obj.(*v1alpha1.InferencePoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inferencePools.
func (c *FakeInferencePools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(inferencepoolsResource, c.ns, opts))

}

// Create takes the representation of a inferencePool and creates it.  Returns the server's representation of the inferencePool, and an error, if there is any.
func (c *FakeInferencePools) Create(ctx context.Context, inferencePool *v1alpha1.InferencePool, opts v1.CreateOptions) (result *v1alpha1.InferencePool, err error) {
	emptyResult := &v1alpha1.InferencePool{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(inferencepoolsResource, c.ns, inferencePool, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.InferencePool), err
}

// Update takes the representation of a inferencePool and updates it. Returns the server's representation of the inferencePool, and an error, if there is any.
func (c *FakeInferencePools) Update(ctx context.Context, inferencePool *v1alpha1.InferencePool, opts v1.UpdateOptions) (result *v1alpha1.InferencePool, err error) {
	emptyResult := &v1alpha1.InferencePool{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(inferencepoolsResource, c.ns, inferencePool, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.InferencePool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInferencePools) UpdateStatus(ctx context.Context, inferencePool *v1alpha1.InferencePool, opts v1.UpdateOptions) (result *v1alpha1.InferencePool, err error) {
	emptyResult := &v1alpha1.InferencePool{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(inferencepoolsResource, "status", c.ns, inferencePool, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.InferencePool), err
}

// Delete takes name of the inferencePool and deletes it. Returns an error if one occurs.
func (c *FakeInferencePools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(inferencepoolsResource, c.ns, name, opts), &v1alpha1.InferencePool{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInferencePools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(inferencepoolsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.InferencePoolList{})
	return err
}

// Patch applies the patch and returns the patched inferencePool.
func (c *FakeInferencePools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InferencePool, err error) {
	emptyResult := &v1alpha1.InferencePool{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(inferencepoolsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.InferencePool), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied inferencePool.
func (c *FakeInferencePools) Apply(ctx context.Context, inferencePool *apiv1alpha1.InferencePoolApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.InferencePool, err error) {
	if inferencePool == nil {
		return nil, fmt.Errorf("inferencePool provided to Apply must not be nil")
	}
	data, err := json.Marshal(inferencePool)
	if err != nil {
		return nil, err
	}
	name := inferencePool.Name
	if name == nil {
		return nil, fmt.Errorf("inferencePool.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.InferencePool{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(inferencepoolsResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.InferencePool), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeInferencePools) ApplyStatus(ctx context.Context, inferencePool *apiv1alpha1.InferencePoolApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.InferencePool, err error) {
	if inferencePool == nil {
		return nil, fmt.Errorf("inferencePool provided to Apply must not be nil")
	}
	data, err := json.Marshal(inferencePool)
	if err != nil {
		return nil, err
	}
	name := inferencePool.Name
	if name == nil {
		return nil, fmt.Errorf("inferencePool.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.InferencePool{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(inferencepoolsResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.InferencePool), err
}
