/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// LLMServiceSpecApplyConfiguration represents a declarative configuration of the LLMServiceSpec type for use
// with apply.
type LLMServiceSpecApplyConfiguration struct {
	Models  []ModelApplyConfiguration `json:"models,omitempty"`
	PoolRef []v1.ObjectReference      `json:"poolRef,omitempty"`
}

// LLMServiceSpecApplyConfiguration constructs a declarative configuration of the LLMServiceSpec type for use with
// apply.
func LLMServiceSpec() *LLMServiceSpecApplyConfiguration {
	return &LLMServiceSpecApplyConfiguration{}
}

// WithModels adds the given value to the Models field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Models field.
func (b *LLMServiceSpecApplyConfiguration) WithModels(values ...*ModelApplyConfiguration) *LLMServiceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithModels")
		}
		b.Models = append(b.Models, *values[i])
	}
	return b
}

// WithPoolRef adds the given value to the PoolRef field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PoolRef field.
func (b *LLMServiceSpecApplyConfiguration) WithPoolRef(values ...v1.ObjectReference) *LLMServiceSpecApplyConfiguration {
	for i := range values {
		b.PoolRef = append(b.PoolRef, values[i])
	}
	return b
}
