/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// LLMServerPoolSpecApplyConfiguration represents a declarative configuration of the LLMServerPoolSpec type for use
// with apply.
type LLMServerPoolSpecApplyConfiguration struct {
	ServiceRefs []v1.ObjectReference `json:"serviceRefs,omitempty"`
}

// LLMServerPoolSpecApplyConfiguration constructs a declarative configuration of the LLMServerPoolSpec type for use with
// apply.
func LLMServerPoolSpec() *LLMServerPoolSpecApplyConfiguration {
	return &LLMServerPoolSpecApplyConfiguration{}
}

// WithServiceRefs adds the given value to the ServiceRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ServiceRefs field.
func (b *LLMServerPoolSpecApplyConfiguration) WithServiceRefs(values ...v1.ObjectReference) *LLMServerPoolSpecApplyConfiguration {
	for i := range values {
		b.ServiceRefs = append(b.ServiceRefs, values[i])
	}
	return b
}
