/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ModelApplyConfiguration represents a declarative configuration of the Model type for use
// with apply.
type ModelApplyConfiguration struct {
	Name         *string                         `json:"name,omitempty"`
	Objective    *ObjectiveApplyConfiguration    `json:"objective,omitempty"`
	TargetModels []TargetModelApplyConfiguration `json:"targetModels,omitempty"`
}

// ModelApplyConfiguration constructs a declarative configuration of the Model type for use with
// apply.
func Model() *ModelApplyConfiguration {
	return &ModelApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ModelApplyConfiguration) WithName(value string) *ModelApplyConfiguration {
	b.Name = &value
	return b
}

// WithObjective sets the Objective field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Objective field is set to the value of the last call.
func (b *ModelApplyConfiguration) WithObjective(value *ObjectiveApplyConfiguration) *ModelApplyConfiguration {
	b.Objective = value
	return b
}

// WithTargetModels adds the given value to the TargetModels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetModels field.
func (b *ModelApplyConfiguration) WithTargetModels(values ...*TargetModelApplyConfiguration) *ModelApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetModels")
		}
		b.TargetModels = append(b.TargetModels, *values[i])
	}
	return b
}
