/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"
)

// ObjectiveApplyConfiguration represents a declarative configuration of the Objective type for use
// with apply.
type ObjectiveApplyConfiguration struct {
	DesiredAveragePerOutputTokenLatencyAtP95OverMultipleRequests *time.Duration `json:"desiredAveragePerOutputTokenLatencyAtP95OverMultipleRequests,omitempty"`
}

// ObjectiveApplyConfiguration constructs a declarative configuration of the Objective type for use with
// apply.
func Objective() *ObjectiveApplyConfiguration {
	return &ObjectiveApplyConfiguration{}
}

// WithDesiredAveragePerOutputTokenLatencyAtP95OverMultipleRequests sets the DesiredAveragePerOutputTokenLatencyAtP95OverMultipleRequests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredAveragePerOutputTokenLatencyAtP95OverMultipleRequests field is set to the value of the last call.
func (b *ObjectiveApplyConfiguration) WithDesiredAveragePerOutputTokenLatencyAtP95OverMultipleRequests(value time.Duration) *ObjectiveApplyConfiguration {
	b.DesiredAveragePerOutputTokenLatencyAtP95OverMultipleRequests = &value
	return b
}
