/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// LLMServerPoolListerExpansion allows custom methods to be added to
// LLMServerPoolLister.
type LLMServerPoolListerExpansion interface{}

// LLMServerPoolNamespaceListerExpansion allows custom methods to be added to
// LLMServerPoolNamespaceLister.
type LLMServerPoolNamespaceListerExpansion interface{}

// LLMServiceListerExpansion allows custom methods to be added to
// LLMServiceLister.
type LLMServiceListerExpansion interface{}

// LLMServiceNamespaceListerExpansion allows custom methods to be added to
// LLMServiceNamespaceLister.
type LLMServiceNamespaceListerExpansion interface{}
