/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "inference.k8s.io/llm-instance-gateway/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LLMServerPoolLister helps list LLMServerPools.
// All objects returned here must be treated as read-only.
type LLMServerPoolLister interface {
	// List lists all LLMServerPools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.LLMServerPool, err error)
	// LLMServerPools returns an object that can list and get LLMServerPools.
	LLMServerPools(namespace string) LLMServerPoolNamespaceLister
	LLMServerPoolListerExpansion
}

// lLMServerPoolLister implements the LLMServerPoolLister interface.
type lLMServerPoolLister struct {
	listers.ResourceIndexer[*apiv1alpha1.LLMServerPool]
}

// NewLLMServerPoolLister returns a new LLMServerPoolLister.
func NewLLMServerPoolLister(indexer cache.Indexer) LLMServerPoolLister {
	return &lLMServerPoolLister{listers.New[*apiv1alpha1.LLMServerPool](indexer, apiv1alpha1.Resource("llmserverpool"))}
}

// LLMServerPools returns an object that can list and get LLMServerPools.
func (s *lLMServerPoolLister) LLMServerPools(namespace string) LLMServerPoolNamespaceLister {
	return lLMServerPoolNamespaceLister{listers.NewNamespaced[*apiv1alpha1.LLMServerPool](s.ResourceIndexer, namespace)}
}

// LLMServerPoolNamespaceLister helps list and get LLMServerPools.
// All objects returned here must be treated as read-only.
type LLMServerPoolNamespaceLister interface {
	// List lists all LLMServerPools in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.LLMServerPool, err error)
	// Get retrieves the LLMServerPool from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.LLMServerPool, error)
	LLMServerPoolNamespaceListerExpansion
}

// lLMServerPoolNamespaceLister implements the LLMServerPoolNamespaceLister
// interface.
type lLMServerPoolNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.LLMServerPool]
}
